### ISSUE TITLE
soundness: add case for error expressions?

### ISSUE THREAD

**Issue by bennn** [nuprl/tag-sound#30]
Type soundness says:

> if `\vdash e : \tau` then `\vdash_H e : \tau` and either
- e --> v and `\vdash_H v : \tau`
- e --> BoundaryErr
- e --> E[dyn ... e'] and e' -> TagErr
- e diverges

This isn't true if `e = TagErr` or `e = BoundaryErr` or contains an error somewhere

should we change the last line of the theorem to say
- e diverges or e = E[Err]
?

**Comment by mfelleisen** [comment]
e is usually taken from the source language, which does not contain Error.
